name: DevSecOps Hybrid SaaS Pipeline
on: [push]
jobs:
  sast-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Semgrep SaaS Scan
        run: |
          python3 -m pip install semgrep
          semgrep ci
        env:
          SEMGREP_APP_TOKEN: 961685994ba84c6f7d96f8b54421d78895d8a89c2c0a2198b7c7b3cfb9a3f620

  dast-scan:
    runs-on: ubuntu-latest
    needs: sast-scan
    steps:
      - uses: actions/checkout@v3
      - name: Start Juice Shop
        run: docker compose up -d juice-shop
      - name: StackHawk DAST Scan
        uses: stackhawk/hawkscan-action@v2.1.3
        with:
          apiKey: hawk.Sd37QpqmJasehhD1WXyi.0eyFQu9u1rUYCieE25QJ
          configurationFiles: stackhawk.yml
        env:
          APP_ID: 54058b458d47eb7b119c65a88af187b0db2f779ff99008ae6d4588011abe47bb
